<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXL0pXJg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXL0pXJg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXL0pXJg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXL0pXJg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXL0pXJg\App_KernelDevDebugContainer([
    'container.build_hash' => 'XL0pXJg',
    'container.build_id' => '4c9c3083',
    'container.build_time' => 1650739669,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXL0pXJg');
